INSERT INTO MOTH.REF_MATIERE (CDMATICODE, TXMATILIBELLE) VALUES ('EXPRESSION_ORALE', 'Expression orale');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, TXMATILIBELLE) VALUES ('DICTEE', 'Dictée');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, TXMATILIBELLE) VALUES ('LECTURE', 'Lecture');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, TXMATILIBELLE) VALUES ('ECRITURE', 'Ecriture');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, TXMATILIBELLE) VALUES ('CORAN', 'Coran');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, TXMATILIBELLE) VALUES ('EDUCATION_ISLAMIQUE', 'Education islamique');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, TXMATILIBELLE) VALUES ('ASSIDUITE_COMPORTEMENT', 'Assiduité / Comportement');
