-- cours enfants pour les matières existantes
UPDATE MOTH.REF_MATIERE SET CDMATITYPE = 'ENFANT';

-- Puis on insère les nouvelles matières (adultes)
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, CDMATITYPE) VALUES ('TAJWID_HAFS', 'ADULTE');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, CDMATITYPE) VALUES ('TAFFSIR_CORAN', 'ADULTE');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, CDMATITYPE) VALUES ('NOURANIYA_HAFS', 'ADULTE');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, CDMATITYPE) VALUES ('TAFFSIR_NOMS_ALLAH', 'ADULTE');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, CDMATITYPE) VALUES ('FIQH', 'ADULTE');
INSERT INTO MOTH.REF_MATIERE (CDMATICODE, CDMATITYPE) VALUES ('LANGUE_ARABE', 'ADULTE');

-- Insertion des traductions (cours enfants)
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'EXPRESSION_ORALE', 'Expression orale');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'DICTEE', 'Dictée');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'LECTURE', 'Lecture');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'ECRITURE', 'Ecriture');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'CORAN', 'Coran');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'EDUCATION_ISLAMIQUE', 'Education islamique');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'ASSIDUITE_COMPORTEMENT', 'Assiduité / Comportement');

-- Insertion des traductions (cours adultes)
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'TAJWID_HAFS', 'Tajwid hafs (Théorique, récitation, apprentissage)');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'TAFFSIR_CORAN', 'Taffsir du coran');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'NOURANIYA_HAFS', 'Cours nouraniya hafs');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'TAFFSIR_NOMS_ALLAH', 'Taffsir des noms d''Allah');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'FIQH', 'Fiqh (prière et purification)');
INSERT INTO MOTH.REF_TRADUCTION (CDTRADCLE, CDTRADVALEUR, TXTRADFR) VALUES ('cdmaticode', 'LANGUE_ARABE', 'Langue arabe');