name: 'Setup Maven avec JDK 17'
description: 'Configure JDK 17 avec cache Maven et injecte les variables d environnement nécessaires au build'

inputs:
  maven-command:
    description: 'Commande Maven à exécuter'
    required: true
    default: 'mvn -B package --file pom.xml'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven
      shell: bash
      env:
        DB_PASSWORD: DB_PASSWORD
        DB_USERNAME: DB_USERNAME
        MAIL_SERVICE_USERNAME: MAIL_SERVICE_USERNAME
        MAIL_SERVICE_PASSWORD: MAIL_SERVICE_PASSWORD
        TOKEN_URI: TOKEN_URI
        COOKIE_SECURE: false
        ALLOWED_ORIGINS: http://localhost:3000
        LOGOUT_REDIRECT_URI: http://localhost:3000
        LOGIN_REDIRECT_URI: http://localhost:3000/login
        ISSUER_URI: http://localhost
        RESET_PASSWORD_URI: http://localhost:3000/resetPassword
        JWT_DECODER_URI: http://localhost:8080/api/oauth2/jwks
        DB_LIQ_USERNAME: DB_LIQ_USERNAME
        DB_LIQ_PASSWORD: DB_LIQ_PASSWORD
        ACTIVATION_UTILISATEUR_URI: http://localhost:3000/accountActivation
        RIB_AMC_FILE_LOCATION: RIB_AMC_FILE_LOCATION
        RIB_AMC_MAIL_ATTACHMENT_NAME: RIB_AMC_MAIL_ATTACHMENT_NAME
        RESOURCE_LOCK_TIMEOUT: 10
        DB_URL: jdbc:postgresql://localhost:5432/mosqueethonon
      run: ${{ inputs.maven-command }}
