CREATE SCHEMA IF NOT EXISTS MOTH;
CREATE SEQUENCE IF NOT EXISTS MOTH.INSCRIPTION_NOINSCINSCRIPTION_SEQ INCREMENT BY 1 START WITH 1000;
DROP ALIAS IF EXISTS moth.getAnneeScolaire;
CREATE ALIAS moth.getAnneeScolaire FOR "org.mosqueethonon.utils.FunctionSQLMocks.getAnneeScolaire";