name: Stop Mosquée Thonon backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement (staging | production)'
        required: true
        default: 'staging'

jobs:

  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop application
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.TARGET_SERVER_IP }} "sudo systemctl stop mosqueethononapp-${{ github.event.inputs.environment }}.service"
