name: Stop Mosquée Thonon backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement (staging | production)'
        required: true
        default: 'staging'

jobs:

  runs-on: ubuntu-latest
  steps:
    - name: Stop application
      run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.TARGET_SERVER_IP }} "sudo systemctl stop mosqueethononapp-${{ github.event.inputs.environment }}.service"
