on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Version à releaser (par 1.0.0)'
        required: true

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }} # branche sur laquelle on a déclenché la création du tag (branche de release)

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Update version
        run: |
          git config --global user.name "Aymen"
          git config --global user.email "aymen330d@hotmail.fr"
          #git checkout -b new-tag-released-${{ github.event.inputs.tag_version }}
          mvn versions:set -DnewVersion=${{ github.event.inputs.tag_version }}  
          #git add pom.xml
          #git commit -m "tag created ==> ${{ github.event.inputs.tag_version }}"
          #git push origin new-tag-released-${{ github.event.inputs.tag_version }} # on pousse les modif sur la nouvelle branche

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_GITHUB }}
          branch: new-tag-released-${{ github.event.inputs.tag_version }}
          base: ${{ github.ref }}
          title: "Update version release after released tag"
          body: "Update version release after released tag"
          draft: false

      - name: Create tag
        run: | 
          git tag ${{ github.event.inputs.tag_version }}
          git push origin ${{ github.event.inputs.tag_version }} #on pousse le nouveau tag
          
          
